base_url = "https://parnianlali.github.io/cv/"
languageCode = "en"
title = 'CV | Parnian'
disableKinds = ["taxonomy", "term"]

defaultContentLanguage = 'en'
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    [languages.en.params]
      datasource = 'content.en'
